import org.gradle.api.file.FileSystemOperations
import java.util.Properties
import javax.inject.Inject

// AGP 9 ships built-in Kotlin support, so org.jetbrains.kotlin.android must NOT be
// applied. The Compose compiler plugin is still required separately on Kotlin 2.x.
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.google.services)
}

// Release signing is read from keystore.properties when present. The original
// siren-release.jks was lost with the old project folder, so a fresh key is
// generated by tools/make-keystore.ps1 — see step.txt section 5.
val keystorePropsFile = rootProject.file("keystore.properties")
val keystoreProps = Properties().apply {
    if (keystorePropsFile.exists()) keystorePropsFile.inputStream().use { load(it) }
}

android {
    namespace = "com.siren.mobile"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.research.siren"
        minSdk = 24
        targetSdk = 35
        versionCode = 5
        versionName = "2.7.0"
        vectorDrawables { useSupportLibrary = true }
    }

    signingConfigs {
        if (keystorePropsFile.exists()) {
            create("release") {
                storeFile = rootProject.file(keystoreProps.getProperty("storeFile"))
                storePassword = keystoreProps.getProperty("storePassword")
                keyAlias = keystoreProps.getProperty("keyAlias")
                keyPassword = keystoreProps.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ""
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = true
            // Left off deliberately. Release builds also SHORTEN resource paths
            // (res/raw/siren_alarm.mp3 becomes res/dQ.mp3), which makes "is the alarm
            // audio still in the APK?" easy to answer wrongly — check by byte size,
            // not filename. Shrinking is off until that retention is re-verified,
            // because a silently muted alarm is the worst failure this app has.
            isShrinkResources = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (keystorePropsFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

/*
 * AGP 9's com.android.kotlin.multiplatform.library plugin does NOT package Compose
 * Multiplatform resources into the AAR — `shared.aar` ships with zero asset entries,
 * and only the iOS targets get assembled resources. Without this copy the shared
 * screens compile fine but Res.drawable.ic_sg_* / Res.font.inter_* fail at runtime.
 *
 * The Android resource reader looks for assets/composeResources/<id>/..., where <id>
 * MUST equal `packageOfResClass` from shared/build.gradle.kts — the generated
 * accessors hard-code that exact prefix. Getting it wrong does not fail the build:
 * every font and drawable simply fails to load at runtime, and because
 * sirenTypography() runs inside SirenTheme the app dies on launch.
 *
 * Confirm against the generated source after changing it:
 *   shared/build/generated/compose/resourceGenerator/kotlin/commonResClass/.../Res.kt
 *   -> private const val MD: String = "composeResources/<id>/"
 */
abstract class CopyComposeResourcesTask : DefaultTask() {
    @get:InputDirectory
    abstract val sourceDir: DirectoryProperty

    @get:Input
    abstract val resourceId: Property<String>

    /** Wired as an assets source directory by the Variant API below. */
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Inject
    abstract val fs: FileSystemOperations

    @TaskAction
    fun copyFiles() {
        // Wipe stale output first: changing resourceId leaves the previous directory
        // behind and BOTH get packaged, shipping two copies of every asset.
        fs.delete { delete(outputDir) }
        fs.copy {
            from(sourceDir)
            into(outputDir.get().dir("composeResources/${resourceId.get()}"))
        }
    }
}

val copySharedComposeResources =
    tasks.register<CopyComposeResourcesTask>("copySharedComposeResources") {
        sourceDir.set(rootProject.file("shared/src/commonMain/composeResources"))
        resourceId.set("com.siren.mobile.resources")
    }

androidComponents {
    onVariants { variant ->
        variant.sources.assets?.addGeneratedSourceDirectory(
            copySharedComposeResources,
            CopyComposeResourcesTask::outputDir,
        )
    }
}

dependencies {
    // All UI, models and the data layer now live in the shared Multiplatform module.
    implementation(project(":shared"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.splashscreen)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    // Firebase drags in fragment 1.1.0 transitively; registerForActivityResult needs
    // >= 1.3.0 or lintVitalRelease fails (InvalidFragmentVersionForActivityResult).
    implementation(libs.androidx.fragment)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    debugImplementation(libs.androidx.ui.tooling)

    // Cloud Messaging is not wrapped by GitLive, so the FCM service stays here.
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.messaging)
}
