import SwiftUI
import ComposeApp

/// Hosts the shared Compose UI. `MainViewControllerKt` is generated by Kotlin/Native
/// from shared/src/iosMain/kotlin/com/siren/mobile/MainViewController.kt.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard) // Compose handles the keyboard inset itself
    }
}
